# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-17 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donator',
            old_name='donation_made',
            new_name='donationmade',
        ),
    ]
