# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20181025_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Help Request', 'verbose_name_plural': 'Help Requests'},
        ),
    ]
